// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxYn3A1I4ye0KTTc_lmAvk4AgE1D8muw4',
    appId: '1:466770078012:web:8b834466fb6b35b88bd639',
    messagingSenderId: '466770078012',
    projectId: 'cryptography-firebase',
    authDomain: 'cryptography-firebase.firebaseapp.com',
    storageBucket: 'cryptography-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPcUvJd48DFXwfKE-iN069dvVoXs6t5E',
    appId: '1:466770078012:android:c289aa1d580c18728bd639',
    messagingSenderId: '466770078012',
    projectId: 'cryptography-firebase',
    storageBucket: 'cryptography-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj7MHIg7Lefs-P22NkjLvdX3a1FZyLyjU',
    appId: '1:466770078012:ios:afb2474beb75d2d88bd639',
    messagingSenderId: '466770078012',
    projectId: 'cryptography-firebase',
    storageBucket: 'cryptography-firebase.appspot.com',
    iosBundleId: 'com.example.cryptographyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj7MHIg7Lefs-P22NkjLvdX3a1FZyLyjU',
    appId: '1:466770078012:ios:b15d2e03673a126d8bd639',
    messagingSenderId: '466770078012',
    projectId: 'cryptography-firebase',
    storageBucket: 'cryptography-firebase.appspot.com',
    iosBundleId: 'com.example.cryptographyApp.RunnerTests',
  );
}
